services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: medhealth-db
    restart: unless-stopped
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: meduser
      POSTGRES_PASSWORD: medpass
      POSTGRES_DB: medhealth
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - medhealth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-mail:
    image: postgres:16.0-alpine3.18
    container_name: mail-db
    restart: unless-stopped
    ports:
      - "5401:5432"
    environment:
      POSTGRES_USER: mailuser
      POSTGRES_PASSWORD: mailpass
      POSTGRES_DB: maildb
    volumes:
      - db-mail-data:/var/lib/postgresql/data
    networks:
      - medhealth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: medhealth-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - medhealth-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  eureka:
    build:
      context: ./medHealthEureka
      dockerfile: Dockerfile
    container_name: medhealth-eureka
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - medhealth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./medHealthAPI
      dockerfile: Dockerfile
    container_name: medhealth-api
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medhealth
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672
      SPRING_RABBITMQ_USERNAME: rabbituser
      SPRING_RABBITMQ_PASSWORD: rabbitpass

    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy
    volumes:
      - ./medHealthAPI/src:/app/src
      - ./medHealthAPI/pom.xml:/app/pom.xml
    networks:
      - medhealth-network
    extra_hosts:
      - "localhost:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications:
    build:
      context: ./medHealthNotifications
      dockerfile: Dockerfile
    container_name: medhealth-notifications
    restart: unless-stopped
    env_file:
      - ./medHealthNotifications/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-mail:5432/maildb
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672
      SPRING_RABBITMQ_USERNAME: rabbituser
      SPRING_RABBITMQ_PASSWORD: rabbitpass
    ports:
      - "8082:8082"
    depends_on:
      db-mail:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka:
        condition: service_healthy
    volumes:
      - ./medHealthNotifications/src:/app/src
      - ./medHealthNotifications/pom.xml:/app/pom.xml
    networks:
      - medhealth-network
    extra_hosts:
      - "localhost:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: ./medHealthGateway
      dockerfile: Dockerfile
    container_name: medhealth-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy
    volumes:
      - ./medHealthGateway/src:/app/src
      - ./medHealthGateway/pom.xml:/app/pom.xml
    networks:
      - medhealth-network
    extra_hosts:
      - "localhost:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./medHealthFE
      dockerfile: Dockerfile
    container_name: medhealth-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./medHealthFE:/app
      - /app/node_modules
    networks:
      - medhealth-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/:5173",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  db-mail-data:
  rabbitmq-data:

networks:
  medhealth-network:
    driver: bridge
