spring:
  application:
    name: medHealth
  datasource:
    url: jdbc:postgresql://localhost:5400/medhealth
    username: meduser
    password: medpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses:
    - localhost:5672
    username: rabbituser
    password: rabbitpass
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms
      additional-paths: src/main/java
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
        
broker:
  queue:
    email-name: medHealthEmailQueue  

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081
  error:
    include-stacktrace: never

info:
  app:
    version: @project.version@

api:
  security:
    token:
      secret: f153a0b668051fdf01c0549d2f9febe3
