spring:
  application:
    name: medHealthNotifications
  datasource:
    url: jdbc:postgresql://localhost:5401/maildb
    username: mailuser
    password: mailpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses:
    - localhost:5672
    username: rabbituser
    password: rabbitpass

broker:
  queue:
    email-name: medHealthEmailQueue

server:
  port: 8082
  error:
    include-stacktrace: never

